# 7장 비동기 호출

## 7.3 API 에러 핸들링

### 1. 타입 가드 활용하기

- Axios 라이브러리에서는 Axios 에러에 대해 isAxiosError라는 타입 가드를 제공함
- 위 타입 가드를 직접 사용할 수도 있지만, 서버 에러임을 명확하게 표시하고 서버에서 내려주는 에러 응답 객체에 대해서도 구체적으로 정의함으로써 에러 객체가 어떤 속성을 가졌는지 파악할 수 있음
- 서버에서 전달하는 공통 에러 객체에 대한 타입을 정의할 수 있음

  ```ts
  interface ErrorResponse {
    status: string;
    serverDateTime: string;
    errorCode: string;
    errorMessgage: string;
  }

  //명시적 타입 가드 작성
  function isServerError(error: unknown): error is AxiosError<ErrorResponse> {
    return axios.isAxiosError(error);
  }

  const onClickdeleteHistoryButton = async (id: string) => {
    try {
      await axios.post("https://...", { id });
      alert("성공~");
    } catch (error: unknown) {
      if (isServerError(e) && e.response && e.response.data.errorMessage) {
        serErrorMessage(e.response.data.errorMessage);
        return;
      }

      setErrorMessage("에러~");
    }
  };
  ```

### 2. 에러 서브클래싱하기

- 단순 서버 에러이외에도 인증 정보 에러, 네트워크 에러, 타임 아웃 에러 등 다양한 에러가 발생할 수 있음
- 서브클래싱
  - 기존 클래스를 확장하여 새로운 클래스를 만드는 과정
  - 새로운 클래스는 상위 클래스의 모든 속성과 메서드를 상속받아 사용할 수 있고 추가적인 속성과 메서드를 정의할 수 있음
- 서브클래싱 활용 예시

  - 에러가 발생했을 때 코드상에서 어떤 에러인지 확인 가능
  - 에러 인스턴스가 무엇인지에 따라 에러 처리 방식을 다르게 구현할 수 있음

  ```ts
  //에러 객체를 상속한 OrderHttpError, NetworkError, UnauthorizedError 정의
  class OrderHttpError extends Error {
    private readonly privateResponse: AxiosResponse<ErrorResponse> | undefined;

    constructor(message?: string, response?: AxiosResponse<ErrorResponse>) {
      super(message);
      this.name = "OrderHttpError";
      this.privateResponse = response;
    }

    get reponse(): AxiosResponse<ErrorResponse> | undefined {
      return this.privateResponse;
    }
  }

  class NetworkError extends Error {
    constructor(message = "") {
      super(message);
      this.name = "NetworeError";
    }
  }

  class UnathorizedError extends Error {
    constructor(message: string, response?: AxiosResponse<ErrorResponse>) {
      super(message, response);
      this.name = "UnauthorizedError";
    }
  }

  //Axios 사용하고 있는 경우, 인터셉터에서 적합한 에러 객체를 전달할 수 있음
  const httpErrorHandler = (
    error: AxiosError<ErrorResponse> | Error
  ): Promise<Error> => {
    let promiseError: Promise<Error>;

    if (axios.isAxiosError(error)) {
      if (Object.is(error.code, "ECONNABORTED")) {
        promisError = Promise.reject(new TimeoutError());
      } else if (Object.js(error.mseaage, "Network Error")) {
        promiseError = Promes.reject(new NetworkError(""));
      } else {
        const { response } = error as AxiosError<ErrorResponse>;

        switch (reponse?.status) {
          case HttpStatusCode.UNAUTORIZED:
            promiseError = Promise.reject(
              new UnauthorizedError(response?.data.message, response)
            );
            break;
          default:
            promiseError = Promise.reject(
              new OrderHttpError(response?.data.message, response)
            );
        }
      }
    } else {
      promiseError = Promise.reject(error);
    }

    return promiseError;
  };

  apiRequester.interceptors.response.use(
    (reponse: AxiosResponse) => reponse,
    httpErrorHandler
  );

  //요청 코드
  const onActionError = (
    error: unknown,
    params?: Omit<AlertPopup, "type" | "message">
  ) => {
    if (error instanceof UnauthorizedError) {
      onUnauthorizedError(
        error.message,
        errorCallback?.onUnauthorizedErrorCallback
      );
    } else if (error instanceof NetworkError) {
      alert("네트워크 에러", {
        onClose: errorCallback?.onNetworkErrorCallback,
      });
    } else if (error instanceof OrderHttpError) {
      alert(error.message, params);
    } else if (error instanceof Error) {
      alert(error.message, params);
    } else {
      alert(defaultHttpErrorMessage, params);
    }
  };

  const getOrderHistory = async (page: number): Promise<History> => {
    try {
      const { data } = await fetchOrderHistory({ page });

      return data;
    } catch (error) {
      onActionsError(error);
    }
  };
  ```

### 3. 인터셉터를 활용한 에러 처리

- HTTP 에러에 일관된 로직을 적용할 수 있음

```ts
const httpErrorHandler = (
  error: AxiosError<ErrorResponse> | Error
): Promise<Error> => {
  (error) => {
    if (error.response && error.reponse.status === 401) {
      window.location.href = `${backOfficeAuthHost}/login?targtUrl=${window.location.href}`;
    }
    return Promise.reject(error);
  };
};

orderApiRequester.interceptors.response.use(
  (reponse: AxiosResponse) => reponse,
  httpErrorHandler
);
```

### 4. 에러 바운더리를 활용한 에러 처리

- 에러 바운더리: 리액트 컴포넌트 트리에서 에러가 발생할 때 공통으로 에러를 처리하는 리액트 컴포넌트
- 리액트 컴포넌트 트리 하위에 있는 컴포넌트에서 발생한 에러를 캐치하고, 해당 에러를 가장 가까운 부모 에러 바운더리에서 처리할 수 있음
- 에러가 발생한 컴포넌트 대신에 에러 처리를 하거나 예상치 못한 에러를 공통 처리할 때 사용할 수 있음

```ts
interface ErrorBoundaryProps {}
interface ErrorBoundaryState {
  hasError: boolean;
}

class ErrorBoundary extends React.Component<
  ErrorBoundaryProps,
  ErrorBoundaryState
> {
  constructor(props: ErrorBoundraryProps) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(): errorBoundaryState {
    return { hasError: true };
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo): void {
    this.setState({ hasError: true });
    console.error(error, errorInfo);
  }

  render(): React.ReactNode {
    const { children } = this.props;
    const { hasError } = this.state;
    return hasError ? <ErrorPage /> : children;
  }
}

const App = () => {
  return (
    <ErrorBoundary>
      <OrderHistoryPage />
    </ErrorBoundary>
  );
};
```

- OrderHistoryPage 컴포넌트 내에서 처리되지 않은 에러가 있을 경우 에러 바운더리에서 에러 페이지를 노출함
- 에러바운더리에 로그를 보내는 코드를 추가하여 예상치 못한 에러의 발생 여부를 추적할 수 있게 됨

### 5. 상태 관리 라이브러리에서의 에러 처리

- Redux의 에러 처리

```ts
//api 호출에 관한 api call reducer
const apiCallSlice = createSlice({
  name: "apiCall",
  initialState,
  reducers: {
    setApiCall: (state, { payload: { status, urlInfo } }) => {
      /* api state를 채우는 로직*/
    },
    setApiCallError: (state, { payload }: PayloadAction<any>) => {
      state.error = payload;
    },
  },
});

const API = axios.create();

const setaxiosInterceptor = (store: EnhancedStroe) => {
  //중복 코드 생략

  //onSuccess시 처리를 인터셉터로 처리
  API.interceptors.response.use(
    (response: AxiosResponse) => {
      const { method, url } = reponse.config;

      sotre.dispatch(
        setApiCall({
          status: ApiCallstauts.None,
          urlInfo: { url, method },
        })
      );

      return response?.data?.data || response?.data;
    },
    (error: AxiosError) => {
      //에러 상태를 관리하지 않고 처리할 수 있는 경우 바로 처리
      if (error.response?.status === 401) {
        window.location.href = error.response.headers.location;
        return;
      } else if (error.response?.stateu === 403) {
        window.location.href = error.response.headers.location;
        return;
      } else {
        message.error("error");
      }

      const {
        config: { url, method },
      } = error;

      store.dispatch(
        setApiCall({
          status: ApiCallStatus.None,
          urlInfo: { url, method },
        })
      );

      return Promise.reject(error);
    }
  );
};

const fetchmenu = createAsyncThunk(
    FETCH_MENU_REQUESTm
    async({shopId, menuId}:FetchMenu) => {
        try{
            const data = await api.fetchMenu(shopId, menuId)
            return data
        }catch(error) {
            //에러를 상태로 처리
            setApiCallError({error})
        }
    }
)
```

```ts
class JobStore {
  job: Job[] = [];
  state: LoadingState = "PENDING";
  errorMsg = "";

  constructor() {
    makeAutoObservable(this);
  }

  async fetchJobList() {
    this.jobs = [];
    this.state = "PENDING";
    this.errorMsg = "";

    try {
      const projects = await fetchJobLsit();
      runInAction(() => {
        this.projects = projects;
        this.state = "DONE";
      });
    } catch (e) {
      runInAction(() => {
        this.state = "ERROR";
        this.errorMsg = e.messgae;
        showAlert();
      });
    }
  }

  get isLoading(): boolean {
    return state === "PENDING";
  }
}

const JobList=()=>{
    const [jobStore] = useState(() => new JobStroe())

    if(jobStore.isLoading) {
        return <div>loading</div>;
    }

    return <>jobStore.jobs.map((job)=><Item job={job}/>)</>
}
```

### 6. react-query를 활용한 에러 처리

- 데이터 패칭 라이브러리를 사용하면 요청에 대한 상태를 반환해 줌 -> 요청 상태를 확인하기 쉬움

```ts
const JobComponent: React.FC = () => {
  const { isError, error, isLoading, data } = useFetchJobList();

  if (isError) {
    return <div>{error}</div>;
  }

  if (isLoading) return <div>loading</div>;

  return <>{data}</>;
};
```

### 7. 그 밖의 에러 처리

- 비즈니스 로직에서의 유효성 검증에 의해 추가된 커스텀 에러는 200 응답과 함께 응답 바디에 별도의 상태 코드를 전달하는 경우 존재
- 이러한 상황에서 커스텀 에러를 어떻게 구현하고 처리할 지 예시

  - 200번 대 성공 응답에 대한 에러 처리가 필요한 경우

  ```ts
  const successHandler = (response: CreateOrderResponse) =>{
      if(resonse.status ==== 'SUCCESS') {
          return;
      }

      throw new CustomError(response.status, response.message)
  }

  const createOrder=(data:CreateOrderData) => {
      try{
          const repsonse = apiRequester.post('https://...',data)

          successHandler(response)
      }catch(error) {
          errorHandler(error)
      }
  }
  ```

  - API가 많을 때는 매번 `if(reponse === 'SUCCESS')`구문을 추가해줘야 함
  - 커스텀 에러를 사용하고 있는 요청을 일괄적으로 에러로 처리하고 싶은 경우 Axios 등의 라이브러리 기능을 활용하면 됨
  - 특정 호스트에 대한 API requester를 별도로 선언하고 상태 코드 비교 로직을 인터셉터에 추가할 수 있음

    ```ts
    export const apiRequester: AxiosInstance = axios.create({
      baseURL: orderApiBaseUrl,
      ...defaultConfig,
    });

    export const httpSuccessHandler = (response: AxiosResponse) => {
      if (response.data.statue !== "SUCCESS") {
        throw new CustomError(response?.data.message, response);
      }

      return response;
    };

    apiRequester.interceptors.response.use(
      httpSuccesshandler,
      httpErrorHandler
    );

    const crateOrder = (data: CreateOrderData) => {
      try {
        const res = apiRequester.post("https://", data);

        successHandler(response);
      } catch (error) {
        //status가 Success가 아닌 경우 에러로 전달됨
        errorHandler(error);
      }
    };
    ```

    - 인터셉터에서 커스텀 에러를 판단하고 에러를 던짐 -> 외부에서 200번대로 온 응답이라도 400번대, 500번대와 같은 에러로 받게 됨
    - 이후 성공 핸들러에서는 성공인 경우이 동작만 작성, 에러 핸들러에서 커스텀 에러 처리
