# API 에러 핸들링

타입스크립트에서 에러를 처리하고 명시하는 방법

## 1. 타입 가드 활용하기

- Axios 라이브러리 : isAxiosError라는 타입 가드를 제공!
- 서버 에러임을 명확하게 표시하고 서버에서 내려주는 에러 응답 객체에 대해서도 구체적으로 정의함으로써 에러 객체가 어떤 속성을 가졌는지 파악할 수 있다.

```tsx
// 공통 에러객체에 대한 타입

interface ErrorResponse {
  status: string;
  serverDateTime: string;
  errorCode: string;
  errorMessage: string;
}
```

- `ErrorResponse` 인터페이스를 사용하여 `AxiosError<ErrorResponse>`형태로 Axios 에러 표현 가능

 ⇒  사용자 정의 타입가드를 사용하여 명시적으로 작성할 수 있다! 

```tsx
function isServerError(error: unknown): error is AxiosError<ErrorResponse> {
  return axios.isAxiosError(error);
}

const onClickDeleteHistoryButton = async (id: string) => {
  try {
    await axios.post('URL', { id });
    alert('주문내역 삭제');
  } catch (e: unknown) {
    // 에러가 Axios 에러이며 ErrorResponse의 형태를 지니고 있고, 서버 응답이 존재하며, 그 응답에는 errorMessage 속성이 존재하는 경우
    if (isServerError(e) && e.response && e.response.data.errorMessage) {
      // true일 경우 명시적으로 서버 에러를 처리하고 에러 메시지를 설정
      setErrorMessage(e.response.data.errorMessage);
    }
    // false일 경우 일반적인 일시적인 에러 메시지를 설정
    setErrorMessage('일시적인 에러가발생했습니다. 잠시 후 다시 시도해주세요');
  }
};
```

## 2. 에러 서브클래싱하기

- 에러는 서버 뿐 아니라 인증, 네트워크, 타임아웃 등 다양한 원인으로 발생하는 바, 이를 명시적으로 표시하기 위해 서브클래싱을 활용할 수 있다.

> 🤔 서브클래싱(SubClassing)이란? </br>
-기존 클래스를 확장하여 새로운 클래스를 만드는 과정 </br>
-새로운 클래스는 상위 클래스의 모든 속성과 메소드를 상속받아 사용할 수 있고, 추가 속성과 메소드를 정의할 수 있다
> 

```tsx
// 기존 코드 : 에러 발생시 에러에 담긴 메세지를 사용자에게 altert로 보여준다
const getOrderHistory = async (page:number) => Promise<History> {
  try {
    const data = await axios.get("APIURL");
    const history = await JSON.parse.(data);
    } catch (e) {
      alert(e.message)
    }
  }
```

```tsx
// 서브클래싱을 활용하기 위한 에러 클래스 정의
class OrderHttpError extends Error {

  private readonly privateResponse: AxiosResponse<ErrorResponse : undfiend>

  constructor(message?: string, response?:AxiosResponse<ErrorResponse>){
    super(message);
    this.name = "OrderHttpError"
    this.privateResponse = response
  }

  get response(): AxiosResponse<ErrorResponse> | undfined {
    return this.privateResponse
  }
}

class NetworkError extends Error{
    constructor(message: ""){
    super(message);
    this.name = "NetworkError"
  }
}

class UnauthorizedError extends Error{
    constructor(message?: string, response?:AxiosResponse<ErrorResponse>){
    super(message, response);
    this.name = "Unauthorized"
  }
}
```

```tsx
//예시 1. 주문 내역을 가져오면서 에러가 발생한 경우의 예시
const fetchOrderHistory = async () => {
  try {
    const response = await apiRequester.get('/order-history');
    console.log('Order history data received:', response.data);
  } catch (error: unknown) {
    if (error instanceof AxiosError) {
      if (error.response) {
        const { status, data } = error.response;
        const { errorCode, errorMessage } = data;

        if (status === 401) {
          // UnauthorizedError
          throw new UnauthorizedError(errorMessage, error.response);
        } else {
          // OrderHttpError
          throw new OrderHttpError(errorMessage, error.response);
        }
      } else if (error.request) {
        // 요청 전송 후 응답이 없는 경우
        throw new NetworkError('No response received');
      } else {
        // 요청 전송 전에 에러가 발생한 경우
        throw new NetworkError('Request error');
      }
    } else {
      // Axios 에러가 아닌 경우
      throw error;
    }
  }
};
```

## 3. 인터셉터를 활용한 에러 처리

- Axios에서 제공하는 interceptors 기능을 사용하면 HTTP에러에 일관된 로직을 적용할 수 있다.

> 🤔Axios Interceptors 어떻게 쓰지?</br>
axios.interceptors.response.use() 형태 </br>
use 함수에 두 개의 콜백 함수를 매개변수로 전달할 수 있다 </br>
       - 첫 번째 함수 (onFulfilled):  성공적으로 응답을 받았을 때 호출 </br>
       - 두 번째 함수 (onRejected): 응답이 실패했을 때, 즉 HTTP 요청이 실패하거나 서버에서 에러 응답을 반환했을 때 호출 </br>
    
> 


```tsx
const httpErrorHandler = (
  error: AxiosError<ErrorResponse> | Error
): Promise<Error> => {
  (error) => {
    if (error.response && error.response.stauts === '401') {
      window.location.href = `/login`;
    }
    return Promise.reject(error);
  };
};

orderApiRequester.interceptors.response.use(
  // 응답 성공시
  (response: AxiosResponse) => response,
  // 응답 실패시 httpErrorHandler() 호출
  httpErrorHandler
);
```

## 4. 에러 바운더리를 활용한 에러 처리

> 🤔에러 바운더리가 뭐지? </br>
- 리액트 컴포넌트 트리에서 에러가 발생했을 때 공통으로 에러를 처리하는 리액트 컴포넌트
> 

- 리액트 컴포넌트 트리 하위에 있는 커포넌트에서 발생한 에러를 캐치하고, `가장 가까운 부모` 에러 바운더리에서 처리 가능
- `에러 발생 컴포넌트 대신에 에러를 처리`하거나, `예상치 못한 에러를 공통으로 처리`해야 할 때

```tsx
import React, { Component, ErrorInfo, ReactNode } from 'react';

interface ErrorBoundaryProps {
  children: ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
}

class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false };
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    console.error('에러가 발생했습니다:', error, errorInfo);
    this.setState({ hasError: true });
  }

  render() {
    if (this.state.hasError) {
      // 에러가 발생했을 때 에러 페이지를 보여줄 수 있는 컴포넌트를 리턴
      return <ErrorPage />;
    }

    return this.props.children;
  }
}

function App() {
  return (
    <ErrorBoundary>
      <OrderHistoryPage />
    </ErrorBoundary>
  );
}

export default App;
```

## 5. 상태관리 라이브러리에서 에러 처리

```tsx
import { atom, useAtom } from 'jotai';

// 에러 상태를 위한 atom 정의
const errorAtom = atom<Error | null>(null);

// fetchData 함수 정의: 비동기 작업을 수행하고 에러를 처리하는 함수
async function fetchData() {
  try {
    // 비동기 작업 수행 (예: API 호출)
    const response = await apiRequester.get('/data');
    const data = response.data;
    
    // 데이터 처리 등 필요한 작업 수행
  } catch (error) {
    // 에러 발생 시 에러 상태 업데이트
    setError(error);
  }
}

// 컴포넌트 내에서 useAtom을 사용하여 에러 상태를 구독하고 관리
function MyComponent() {
  const [error, setError] = useAtom(errorAtom);

  return (
    <div>
      {/* 에러가 있을 경우 에러 메시지 출력 */}
      {error && <p>Error: {error.message}</p>}
      
      {/* 데이터를 가져오는 버튼 */}
      <button onClick={fetchData}>Fetch Data</button>
    </div>
  );
}
```

## 6. 리액트쿼리를 활용한 에러 처리

- React-Query, swr같은 라이브러리는 요청에 대한 상태를 반환해줌 ⇒ 요청 상태를 확인하기 쉽다!

```tsx
const JobComponent: React.FC = () => {
  // 요청에 대한 상태를 반환
  const { isError, error, isLoading, data } = useFetchJobList();

  // 에러 발생
  if (isError) {
    return <div>{`${error.message}`}가 발생했습니다. 다시 시도해주세요</div>;
  }

  // 로딩
  if (isLoading) {
    return <div>로딩 중입니다</div>;
  }

  // 정상적으로 실행시 화면에 데이터 출력
  return (
    <>
      {data.map((job) => (
        <JobItem key={job.id} job={job} />
      ))}
    </>
  );
};
```

## 7. 그밖의 에러 처리

### 예시: 200응답과 함께 응답 바디에 별도의 상태 코드를 전달하는 커스텀 에러

- 성공 응답에 대한 에러 처리가 필요할 수 있다!

```tsx
//성공 응답이지만 에러 처리가 필요한 응답 예시
httpStatus:200
{
  "status":"C2005",// 응답 바디에 별도의 상태 코드와 메세지 전달
  "message":"장바구니에 품절된 메뉴가 있습니다"
}
```

### 해결책

Axios등의 라이브러리를 사용하여 특정 호스트에 대한 requester를 별도로 선언한다.
이후 상태 코드 비교 로직을 인터셉터에 추가한다.

```tsx
const apiRequester: AxiosInstance = axiost.create({
  baseorderAURL: orderApiBaseUrl,
  ...defaultConfig,
});

export const httpSuccesHandelr = (response: AxiosResponse) => {
  if (response.data.status !== 'SUCCESS') {
    throw new CustomError(response.data.message, response);
  }

  return response;
};

apiRequester.interceptors.response.use(httpSuccesHandelr, httpErrorHandler);

const createOrder = (data: CreateOrderData) => {
  try {
    const response = apiRequester.post('PostUrl', data);
    httpSuccesHandelr(response);
  } catch (e) {
    httpErrorHandler(e);
  }
};
```
